### PR TITLE
Bus Ticketing System- 3rd Iteration

### PR DESCRIPTION
**Pull request by YiTingYR**
The 3rd iteration is begin. These are the csv file for previously two iteration that have been completed.

### CODE REVIEW

**Comment by phoonks** [comment]
i done the user story for the process user login.

**Comment by KolNg** [comment]
I have added a user story which is Process User Removal into current backlog.

**Comment by YiTingYR** [comment]
I have added user stories for ticket change and delete trip module into current backlog.

**Comment by YiTingYR** [comment]
ticket change module has allocated for kol, sanjiek and kah seng for the implemetation

**Comment by YiTingYR** [comment]
Delete trip module has allocated for wandao for the implementation

**Comment by YiTingYR** [comment]
sanjiek and yiting are assigned to Process user removal module for the development of module

**Comment by YiTingYR** [comment]
Process user removal module has started

**Comment by phoonks** [comment]
I have added user stories for new user registration module into current backlog.

**Comment by phoonks** [comment]
Ticket change module has started.

**Comment by YiTingYR** [comment]
wandao and kol are assigned to new user registration module

**Comment by sanjiek** [comment]
I have added the user story of process password change into current backlog.

**Comment by YiTingYR** [comment]
yiting and kahseng assigned to process password change module

**Comment by YiTingYR** [comment]
kahseng, sanjiek and yiting have assigned to process user login module

**Comment by YiTingYR** [comment]
delete trip module has assigned to wandao

**Comment by YiTingYR** [comment]
process user removal module has allocated for sanjiek and yiting

**Comment by WenDaoChan** [comment]
The delete trip module has completed and delivered.

**Comment by WenDaoChan** [comment]
The process new user registration module has completed and delivered.

**Comment by sanjiek** [comment]
the process user removal and process user login module have completed and delivered.

**Comment by KolNg** [comment]
Ticket change task has completed and delivered.

**Comment by YiTingYR** [comment]
ticket change module is accepted

**Comment by YiTingYR** [comment]
process new user registration module is accepted

**Comment by YiTingYR** [comment]
process user removal is accepted

**Comment by YiTingYR** [comment]
process user login module is accepted

**Comment by YiTingYR** [comment]
delete trip module is accepted

**Comment by phoonks** [comment]
the Process Password Change module have completed and delivered.

**Comment by YiTingYR** [comment]
process password change module is accepted

**Pull request merged**
